[demo]
name = "Domain-Based Architecture"
description = "Demonstrates the new domain-based architecture with entities from multiple domains including common, healthcare, and ecommerce"
category = "Domain Architecture"
tags = ["domain", "architecture", "company", "doctor", "product", "medical-device"]
author = "Rapiddweller Asia Co., Ltd."
icon = "🏢"

[files]
main = "datamimic.xml"