title = "Basic Py Scripting"
description = "Showcases the capabilities of Python in combination with DATAMIMIC. Aalso includes the usage of scripted sources and scriptevaluation in templates."
icon = "py"
tags = ["#datamimic", "#python", "#sourcescript"]
projectName = "demo-py-scripting"
id = "demo-py-scripting"
