from collections.abc import Sequence
from typing import TypeVar

_T = TypeVar("_T")

def choice(seq: Sequence[_T]) -> _T: ...
def getone(regex_string: str, limit: int = 20) -> str: ...
def randint(a: int, b: int) -> int: ...
