from datamimic_ce.domains.shared.generator_registry import generator_namespace


def test_builtin_generator_inventory_is_complete():
    assert list(generator_namespace()) == [
        "AcademicTitleGenerator",
        "BinaryGenerator",
        "BirthdateGenerator",
        "BooleanGenerator",
        "CNPJGenerator",
        "ColorGenerator",
        "CompanyNameGenerator",
        "CPFGenerator",
        "DataFakerGenerator",
        "DateTimeGenerator",
        "DepartmentNameGenerator",
        "DomainGenerator",
        "EANGenerator",
        "EmailAddressGenerator",
        "FamilyNameGenerator",
        "FloatGenerator",
        "GenderGenerator",
        "GivenNameGenerator",
        "GlobalIncrementGenerator",
        "HashGenerator",
        "IncrementGenerator",
        "IntegerGenerator",
        "NobilityTitleGenerator",
        "PasswordGenerator",
        "PhoneNumberGenerator",
        "PrefixedIdGenerator",
        "SectorGenerator",
        "SSNGenerator",
        "StateTransitionGenerator",
        "StreetNameGenerator",
        "StringGenerator",
        "TokenGenerator",
        "UrlGenerator",
        "UUIDGenerator",
    ]
