postgresql.db.host=postgres
postgresql.db.port=5432
postgresql.db.database=rd-datamimic
postgresql.db.user=datamimic
postgresql.db.password=datamimic
postgresql.db.dbms=postgresql

mssql.db.host=mssql
mssql.db.port=1433
mssql.db.database=master
mssql.db.user=sa
mssql.db.password=P@ssword123
mssql.db.dbms=mssql

oracle.db.host=oracle
oracle.db.port=1521
oracle.db.database=rddb
oracle.db.user=rdadm
oracle.db.password=rdpassword
oracle.db.dbms=oracle

mysql.db.host=mysql
mysql.db.port=3306
mysql.db.database=rddb
mysql.db.user=root
mysql.db.password=root
mysql.db.dbms=mysql

sqlite.db.database=matrix
sqlite.db.dbms=sqlite
