from collections.abc import Callable
from typing import Generic, TypeVar

T = TypeVar("T")

class ObjectRef(Generic[T]): ...

class RemoteFunction(Generic[T]):
    def options(self, **kwargs: object) -> RemoteFunction[T]: ...
    def remote(self, *args: object, **kwargs: object) -> ObjectRef[T]: ...

def remote(function: Callable[..., T]) -> RemoteFunction[T]: ...

def get(objects: list[ObjectRef[T]]) -> list[T]: ...
def init(**kwargs: object) -> None: ...
