DECLARE
    n NUMBER;
BEGIN
    SELECT COUNT(*) INTO n FROM user_tables WHERE table_name = 'PAGE_ROWS';
    IF n > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE PAGE_ROWS';
    END IF;
    SELECT COUNT(*) INTO n FROM user_tables WHERE table_name = 'PAGE_ROWS_PK';
    IF n > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE PAGE_ROWS_PK';
    END IF;
END;

-- no key; first column grp is not unique, so the old ORDER BY 1 left ties unordered
CREATE TABLE PAGE_ROWS (grp INT, id INT);
-- primary key is not the first column
CREATE TABLE PAGE_ROWS_PK (grp INT, id INT PRIMARY KEY);

INSERT INTO PAGE_ROWS (grp, id) VALUES (2,12);
INSERT INTO PAGE_ROWS (grp, id) VALUES (1,11);
INSERT INTO PAGE_ROWS (grp, id) VALUES (3,10);
INSERT INTO PAGE_ROWS (grp, id) VALUES (2,9);
INSERT INTO PAGE_ROWS (grp, id) VALUES (1,8);
INSERT INTO PAGE_ROWS (grp, id) VALUES (3,7);
INSERT INTO PAGE_ROWS (grp, id) VALUES (2,6);
INSERT INTO PAGE_ROWS (grp, id) VALUES (1,5);
INSERT INTO PAGE_ROWS (grp, id) VALUES (3,4);
INSERT INTO PAGE_ROWS (grp, id) VALUES (2,3);
INSERT INTO PAGE_ROWS (grp, id) VALUES (1,2);
INSERT INTO PAGE_ROWS (grp, id) VALUES (3,1);
INSERT INTO PAGE_ROWS_PK (grp, id) VALUES (2,12);
INSERT INTO PAGE_ROWS_PK (grp, id) VALUES (1,11);
INSERT INTO PAGE_ROWS_PK (grp, id) VALUES (3,10);
INSERT INTO PAGE_ROWS_PK (grp, id) VALUES (2,9);
INSERT INTO PAGE_ROWS_PK (grp, id) VALUES (1,8);
INSERT INTO PAGE_ROWS_PK (grp, id) VALUES (3,7);
INSERT INTO PAGE_ROWS_PK (grp, id) VALUES (2,6);
INSERT INTO PAGE_ROWS_PK (grp, id) VALUES (1,5);
INSERT INTO PAGE_ROWS_PK (grp, id) VALUES (3,4);
INSERT INTO PAGE_ROWS_PK (grp, id) VALUES (2,3);
INSERT INTO PAGE_ROWS_PK (grp, id) VALUES (1,2);
INSERT INTO PAGE_ROWS_PK (grp, id) VALUES (3,1);
